import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import { Toast } from "@heroui/react";
import { Toaster } from 'sonner';

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin","bengali"],
  weight: ["300", "400", "500", "600", "700"],
});



export const metadata: Metadata = {
  title: "বাজার দর",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      data-scroll-behavior="smooth"
      className={`${hindSiliguri.className}  h-full antialiased scroll-smooth`}
    >
      <body suppressHydrationWarning className="min-h-screen flex flex-col">
        <Toast.Provider placement="top" />
        
        <Header></Header>
        <Marquee></Marquee>
        
        <main className="flex-1 bg-[#F0F5F0]">
          {children}
        </main>
        
        <Footer></Footer>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
